//
//  SwiftUIView.swift
//  DrawingPractice
//
//  Created by Labtanza on 7/12/22.
//

import SwiftUI

struct SwiftUIView: View {
    var body: some View {
        Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
    }
}

struct SwiftUIView_Previews: PreviewProvider {
    static var previews: some View {
        SwiftUIView()
    }
}

// This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
// http://www.paintcodeapp.com

//// General Declarations
//let context = UIGraphicsGetCurrentContext()!
//
////// Symbol Drawing
//context.saveGState()
//context.translateBy(x: 47.17, y: 83.5)
//
//let symbolRect = CGRect(x: 0, y: -42, width: 59, height: 42)
//context.saveGState()
//context.clip(to: symbolRect)
//context.translateBy(x: symbolRect.minX, y: symbolRect.minY)
//
//StyleKitName.drawCanvas2(frame: CGRect(origin: .zero, size: symbolRect.size), resizing: .stretch)
//context.restoreGState()
//
//context.restoreGState()
//
